[package]
name = "wallet"
version = "0.1.0"
authors = ["DFINITY Stiftung <sdk@dfinity.org>"]
edition = "2018"

[profile.release]
lto = true
opt-level = 'z'

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
ic-types = "0.1.2"
libflate = "1"
num-traits = "0.2.14"
serde = "1.0.116"
serde_bytes = "0.11"

[dependencies.ic-cdk]
version = "0.2.1"
git = "https://github.com/dfinity/cdk-rs.git"
branch = "pshahi/blob-opt"
rev = "e3c7bff01a4ff275f4e19273a2ff283b58ee4f81"

[dependencies.ic-cdk-macros]
version = "0.2.1"
git = "https://github.com/dfinity/cdk-rs.git"
branch = "pshahi/blob-opt"
rev = "e3c7bff01a4ff275f4e19273a2ff283b58ee4f81"


[dependencies.candid]
version = "0.6.12"
git = "https://github.com/dfinity/candid.git"
branch = "blob-opt"
rev = "75eada49f31773aa87b067a52ba1fa5e99dd09d4"
